// GENERATED — do not edit. Fonte: tokens/tokens.json (npm run build:tokens).
export type ForgeCssVar =
  | "--forge-bg"
  | "--forge-surface"
  | "--forge-surface-raised"
  | "--forge-panel"
  | "--forge-border"
  | "--forge-border-input"
  | "--forge-divider"
  | "--forge-text"
  | "--forge-text-muted"
  | "--forge-text-dim"
  | "--forge-text-faint"
  | "--forge-text-dimmer"
  | "--forge-accent"
  | "--forge-accent-fill"
  | "--forge-on-accent"
  | "--forge-success"
  | "--forge-warning"
  | "--forge-danger"
  | "--forge-danger-fill"
  | "--forge-nutrition"
  | "--forge-macro-protein"
  | "--forge-macro-carb"
  | "--forge-macro-fat"
  | "--forge-cat-1"
  | "--forge-cat-2"
  | "--forge-cat-3"
  | "--forge-cat-4"
  | "--forge-cat-5"
  | "--forge-cat-6"
  | "--forge-cat-ext-1"
  | "--forge-cat-ext-2"
  | "--forge-cat-ext-3"
  | "--forge-cat-ext-4"
  | "--forge-cat-ext-5"
  | "--forge-cat-ext-6"
  | "--forge-cat-ext-7"
  | "--forge-cat-ext-8"
  | "--forge-cat-ext-9"
  | "--forge-scrim"
  | "--forge-scrim-heavy"
  | "--forge-focus-ring"
  | "--forge-negative"
  | "--forge-warn-surface"
  | "--forge-warn-border"
  | "--forge-warn-text"
  | "--forge-on-brand-google-bg"
  | "--forge-on-brand-google-text"
  | "--forge-on-light"
  | "--forge-on-dark"
  | "--forge-font-title"
  | "--forge-font-body"
  | "--forge-weight-title-semi"
  | "--forge-weight-title-bold"
  | "--forge-weight-title-extra"
  | "--forge-weight-body-regular"
  | "--forge-weight-body-medium"
  | "--forge-weight-body-semi"
  | "--forge-weight-body-bold"
  | "--forge-weight-body-extra"
  | "--forge-text-logo-lg"
  | "--forge-text-screen-title"
  | "--forge-text-panel-title"
  | "--forge-text-card-title"
  | "--forge-text-input"
  | "--forge-text-list-item"
  | "--forge-text-body"
  | "--forge-text-body-sm"
  | "--forge-text-chip"
  | "--forge-text-label"
  | "--forge-text-mini-label"
  | "--forge-text-stat"
  | "--forge-text-stat-sm"
  | "--forge-tracking-title"
  | "--forge-tracking-label"
  | "--forge-tracking-eyebrow"
  | "--forge-lh-logo-lg"
  | "--forge-lh-screen-title"
  | "--forge-lh-panel-title"
  | "--forge-lh-card-title"
  | "--forge-lh-input"
  | "--forge-lh-list-item"
  | "--forge-lh-body"
  | "--forge-lh-body-sm"
  | "--forge-lh-chip"
  | "--forge-lh-label"
  | "--forge-lh-mini-label"
  | "--forge-space-0"
  | "--forge-space-2"
  | "--forge-space-4"
  | "--forge-space-6"
  | "--forge-space-8"
  | "--forge-space-10"
  | "--forge-space-12"
  | "--forge-space-16"
  | "--forge-space-20"
  | "--forge-space-24"
  | "--forge-space-32"
  | "--forge-space-40"
  | "--forge-space-screen-h"
  | "--forge-space-card"
  | "--forge-space-gap"
  | "--forge-space-card-gap"
  | "--forge-radius-card"
  | "--forge-radius-panel"
  | "--forge-radius-input"
  | "--forge-radius-button"
  | "--forge-radius-chip"
  | "--forge-radius-pill"
  | "--forge-radius-video"
  | "--forge-size-control-sm"
  | "--forge-size-control-md"
  | "--forge-size-control-lg"
  | "--forge-icon-sm"
  | "--forge-icon-md"
  | "--forge-icon-lg"
  | "--forge-border-w"
  | "--forge-border-w-strong"
  | "--forge-focus-ring-w"
  | "--forge-focus-ring-offset"
  | "--forge-opacity-press"
  | "--forge-opacity-disabled"
  | "--forge-z-nav"
  | "--forge-z-overlay"
  | "--forge-z-fullscreen"
  | "--forge-z-video"
  | "--forge-app-max-width"
  | "--forge-tap-target-min"
  | "--forge-tap-target"
  | "--forge-bp-phone"
  | "--forge-bp-large"
  | "--forge-bp-xlarge"
  | "--forge-duration-instant"
  | "--forge-duration-fast"
  | "--forge-duration-base"
  | "--forge-duration-slow"
  | "--forge-duration-loop-spin"
  | "--forge-duration-loop-pulse"
  | "--forge-ease-standard"
  | "--forge-ease-linear"
  | "--forge-ease-emphasized";

// Forma do objeto `tokens` exportado por tokens/tokens.rn.js (tema dark único),
// gerada do mesmo conjunto de tokens: chaves camelCase, valores resolvidos
// (string p/ cor/família/keyword, number p/ dp/ms).
export interface ForgeTokens {
  "bg": string;
  "surface": string;
  "surfaceRaised": string;
  "panel": string;
  "border": string;
  "borderInput": string;
  "divider": string;
  "text": string;
  "textMuted": string;
  "textDim": string;
  "textFaint": string;
  "textDimmer": string;
  "accent": string;
  "accentFill": string;
  "onAccent": string;
  "success": string;
  "warning": string;
  "danger": string;
  "dangerFill": string;
  "nutrition": string;
  "macroProtein": string;
  "macroCarb": string;
  "macroFat": string;
  "cat1": string;
  "cat2": string;
  "cat3": string;
  "cat4": string;
  "cat5": string;
  "cat6": string;
  "catExt1": string;
  "catExt2": string;
  "catExt3": string;
  "catExt4": string;
  "catExt5": string;
  "catExt6": string;
  "catExt7": string;
  "catExt8": string;
  "catExt9": string;
  "scrim": string;
  "scrimHeavy": string;
  "focusRing": string;
  "negative": string;
  "warnSurface": string;
  "warnBorder": string;
  "warnText": string;
  "onBrandGoogleBg": string;
  "onBrandGoogleText": string;
  "onLight": string;
  "onDark": string;
  "fontTitle": string;
  "fontBody": string;
  "weightTitleSemi": string;
  "weightTitleBold": string;
  "weightTitleExtra": string;
  "weightBodyRegular": string;
  "weightBodyMedium": string;
  "weightBodySemi": string;
  "weightBodyBold": string;
  "weightBodyExtra": string;
  "textLogoLg": number;
  "textScreenTitle": number;
  "textPanelTitle": number;
  "textCardTitle": number;
  "textInput": number;
  "textListItem": number;
  "textBody": number;
  "textBodySm": number;
  "textChip": number;
  "textLabel": number;
  "textMiniLabel": number;
  "textStat": number;
  "textStatSm": number;
  "trackingTitle": number;
  "trackingLabel": number;
  "trackingEyebrow": number;
  "lhLogoLg": number;
  "lhScreenTitle": number;
  "lhPanelTitle": number;
  "lhCardTitle": number;
  "lhInput": number;
  "lhListItem": number;
  "lhBody": number;
  "lhBodySm": number;
  "lhChip": number;
  "lhLabel": number;
  "lhMiniLabel": number;
  "space0": number;
  "space2": number;
  "space4": number;
  "space6": number;
  "space8": number;
  "space10": number;
  "space12": number;
  "space16": number;
  "space20": number;
  "space24": number;
  "space32": number;
  "space40": number;
  "spaceScreenH": number;
  "spaceCard": number;
  "spaceGap": number;
  "spaceCardGap": number;
  "radiusCard": number;
  "radiusPanel": number;
  "radiusInput": number;
  "radiusButton": number;
  "radiusChip": number;
  "radiusPill": number;
  "radiusVideo": number;
  "sizeControlSm": number;
  "sizeControlMd": number;
  "sizeControlLg": number;
  "iconSm": number;
  "iconMd": number;
  "iconLg": number;
  "borderW": number;
  "borderWStrong": number;
  "focusRingW": number;
  "focusRingOffset": number;
  "opacityPress": number;
  "opacityDisabled": number;
  "zNav": number;
  "zOverlay": number;
  "zFullscreen": number;
  "zVideo": number;
  "appMaxWidth": number;
  "tapTargetMin": number;
  "tapTarget": number;
  "bpPhone": number;
  "bpLarge": number;
  "bpXlarge": number;
  "durationInstant": number;
  "durationFast": number;
  "durationBase": number;
  "durationSlow": number;
  "durationLoopSpin": number;
  "durationLoopPulse": number;
  "easeStandard": string;
  "easeLinear": string;
  "easeEmphasized": readonly number[];
  "font": { "titleSemi": string; "titleBold": string; "titleExtra": string; "bodyRegular": string; "bodyMedium": string; "bodySemi": string; "bodyBold": string; "bodyExtra": string };
}

export declare const tokens: ForgeTokens;            // valores do tema dark (único)
